export const ItemActionTypes = {
  SET_CURRENT_ITEM: 'SET_CURRENT_ITEM',
  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
  SET_DETAIL_ITEM: 'SET_DETAIL_ITEM',
  SET_LOVE_ITEM: 'SET_LOVE_ITEM',
  SET_LOVE_DETAIL_ITEM: 'SET_LOVE_DETAIL_ITEM',
}